# Generated by Django 2.1.2 on 2018-11-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sub_toppings', models.ManyToManyField(related_name='_topping_sub_toppings_+', to='presto_api.Topping')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='toppings',
            field=models.ManyToManyField(to='presto_api.Topping'),
        ),
    ]
