# Generated by Django 2.1.2 on 2018-11-14 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presto_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'dish', 'verbose_name_plural': 'dishes'},
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='presto_api.Restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='presto_api.Topping'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='sub_toppings',
            field=models.ManyToManyField(blank=True, related_name='_topping_sub_toppings_+', to='presto_api.Topping'),
        ),
    ]
