# Generated by Django 2.1.2 on 2018-11-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto_api', '0003_auto_20181114_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='sub_toppings',
            field=models.ManyToManyField(blank=True, to='presto_api.Topping'),
        ),
    ]
