# Generated by Django 2.1.2 on 2018-11-14 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presto_api', '0004_auto_20181114_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='sub_toppings',
        ),
        migrations.AddField(
            model_name='topping',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='presto_api.Topping'),
            preserve_default=False,
        ),
    ]
