# Generated by Django 2.1.2 on 2018-11-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presto_api', '0005_auto_20181114_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presto_api.Topping'),
        ),
    ]
