# Generated by Django 2.1.2 on 2018-11-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto_api', '0006_auto_20181114_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='parent',
        ),
        migrations.AddField(
            model_name='topping',
            name='sub_toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='_topping_sub_toppings_+', to='presto_api.Topping'),
        ),
    ]
