# Generated by Django 2.1.2 on 2018-11-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presto_api', '0007_auto_20181114_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='sub_toppings',
        ),
        migrations.AddField(
            model_name='topping',
            name='sub_toppings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='presto_api.Topping'),
        ),
    ]
