# Generated by Django 2.1.2 on 2018-11-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presto_api', '0009_auto_20181114_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_toppings', to='presto_api.Topping'),
        ),
    ]
