# Generated by Django 2.1.2 on 2018-11-15 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presto_api', '0010_auto_20181115_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='base_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='topping',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
